### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by quangtudng** [LE-VAN-KET/nodejs1-sgroup-vanket#1]
[Review-BT2-VanKet.docx](https://github.com/LE-VAN-KET/nodejs1-sgroup-vanket/files/4304621/Review-BT2-VanKet.docx)
Anh gửi review nhé

**Comment by LE-VAN-KET** [comment]
em có để email với password trên file README.md đó anh

**Comment by quangtudng** [comment]
oke e , authentication mình cũng làm sớm thôi ,  trong ngày mai a sẽ đăng post bài tập tiếp
